# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 574dd377111cdaf51f515c1f16c1b79014f2ccff9ca57b4cd11dabba01219dce66e116bddf1aee82da0f122056376fc8e6db3c94242dd0fc31173ae90dcb52ce

test:
  secret_key_base: e1748f65b986769079ce39d0c078f04a9344ac23aa03e1be3b12950a8743bdc0607e2e1699d80cfe21a26ef4324f5ba3b89c5b494d96b1ec75c1218374e79c0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
